version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newserver-php
    volumes:
      - ./tlunews:/var/www/html
    ports:
      - "8080:80"
    networks:
      - web

  mysql:
    image: mysql:8.0
    container_name: newserver-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: QL
    ports:
      - "3306:3306"
    networks:
      - web
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  web:
    driver: bridge
volumes:
  mysql-data:
